### DISCUSSION TITLE
Override fake node name

### DISCUSSION THREAD

**Discussion by mispon** [kubernetes-sigs/kwok#1082] [Q&A] [answered]
Hello!

To test my task, I need to create nodes with a special name. 

I have tried overriding the name with 
```bash
kwokctl scale node --param '.name="new-node-name"'
``` 
and with `KwokctlResource` like this:
```yaml
apiVersion: config.kwok.x-k8s.io/v1alpha1
kind: KwokctlResource
metadata:
  name: node
parameters:
  podCIDR: "10.0.0.1/24"
template: |
  kind: Node
  apiVersion: v1
  metadata:
    name: "new-node-name"
```
but nodes are still created with the default name node-000000.

Is it possible to override the name at the moment?

**Comment by wzshiming** [comment]
The `KwokctlResource` needs to be specified with `--config` or you can add it to ~/.kwok/kwok.yaml, when the cluster is created.

**Reply by mispon** [reply]
@wzshiming hi! yes, it is in my kwok.yaml file
Through the resource, I override the annotations and labels (this works) and the node name (this doesn't work for me)

**Reply by mispon** [reply]
Full kwok.yaml config

```yaml
apiVersion: config.kwok.x-k8s.io/v1alpha1
kind: KwokConfiguration
options:
  manageAllNodes: false
  manageNodesWithAnnotationSelector: 'kwok.x-k8s.io/node=fake'
  nodeLeaseDurationSeconds: 5
  enableCRDs:
---
apiVersion: config.kwok.x-k8s.io/v1alpha1
kind: KwokctlConfiguration
options:
  kubeBinaryPrefix: https://github.com/kwok-ci/k8s/releases/download/v1.29.2-kwok.0-darwin-arm64
  enableCRDs:
---
apiVersion: config.kwok.x-k8s.io/v1alpha1
kind: KwokctlResource
metadata:
  name: node
parameters:
  podCIDR: "10.0.0.1/24"
template: |
  kind: Node
  apiVersion: v1
  metadata:
    name: my-custom-name
    annotations:
      kwok.x-k8s.io/node: fake
      node.alpha.kubernetes.io/ttl: "0"
    labels:
      key: val
  spec:
    podCIDR: {{ AddCIDR .podCIDR Index }}
```
