### DISCUSSION TITLE
How can I simulate different lifecycles for multiple pods and jobs

### DISCUSSION THREAD

**Discussion by restrelas** [kubernetes-sigs/kwok#1340] [Q&A] [answered]
I want to make a simulation in which there will be multiple pods and jobs with different behavior for different timestamps, and then mesure the resource allocation of the nodes at multiple timestamps.

For the pod and job lifecycle I've tried to experiment using the stage CR, however after some days trying I still can't figure it out how to make the pods change state in the simulator.

Is it possible to change the state of pods differently for various timestamps using the simulator? And if so, how can I do it?

**Comment by wzshiming** [comment, marked as answer]
> Is it possible to change the state of pods differently for various timestamps using the simulator? And if so, how can I do it?

You can refer to this [docs](https://kwok.sigs.k8s.io/docs/user/stages-configuration/#pod-stages-that-simulate-real-behavior-as-closely-as-possible), that is [pod-create.yaml](https://github.com/kubernetes-sigs/kwok/blob/main/kustomize/stage/pod/general/pod-create.yaml) -> [pod-init-container-running.yaml](https://github.com/kubernetes-sigs/kwok/blob/main/kustomize/stage/pod/general/pod-init-container-running.yaml) -> [pod-init-container-completed.yaml](https://github.com/kubernetes-sigs/kwok/blob/main/kustomize/stage/pod/general/pod-init-container-completed.yaml) -> [pod-ready.yaml](https://github.com/kubernetes-sigs/kwok/blob/main/kustomize/stage/pod/general/pod-ready.yaml), I think it may be the effect you want if I understand correctly

So basically, the `selector` matches the state, and then how long does it `delay`, and then applies the `next` action, that's a `stage`, and then you need to connect each `stage` step by step. the `selector` matches the `next` of the last `stage` action as connect.

**Comment by restrelas** [comment]
@wzshiming Thanks for explaining the stage configuration, following what you've shown, I think I can simulate the desired behavior using this stage template and specifying the delay of each pod for each stage using a annotation such as '.metadata.annotations["pod-create.stage.kwok.x-k8s.io/delay"]'

However, trying to replicate the stage demo, the stage configuration seem to not be altering the behavior of pods like the demo shows
![kwok-stage-test](https://github.com/user-attachments/assets/8310688e-a189-4e19-92cf-f2aaa6ae269e)

Is there anything I am doing wrong?

**Reply by wzshiming** [reply]
I think you might be confused with `kwokctl` and `kwok in a exist cluster`.

In your attempt, you can just replace `kwokctl` with `kind`, and replace `kwokctl scale node --replicas 2` with [create node](https://kwok.sigs.k8s.io/docs/user/kwok-manage-nodes-and-pods/#create-a-node).


If you want to use `kwokctl`, that's a fake cluster and [all CR is config by default](https://kwok.sigs.k8s.io/docs/user/configuration/), so you need put together all config with `kwokctl create cluster --config`

or you can use `--enable-crds Stage` to enable `stage CRD` and ignore `stage config`, then you need manage all the stage CR by youself.

**Reply by restrelas** [reply]
Thanks for clarifying the CRs configuration of kwok.

I was able to make the the jobs and pods run with the time delay configured in the stage.

Now I'm trying to set up the delay of each stage using a annotation on the job, because I would like that each job/pod 
changed state at a specific time to simulate a dataset.

Here is the YAML file for creating both jobs, one of the jobs has the annotations for a delay of 20 seconds and the other don't.
```
apiVersion: batch/v1
kind: Job
metadata:
  name: test-pod-for-job
spec:
  template:
    spec:
      tolerations:
      - key: "kwok-controller/provider"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: job
        image: fake
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-pod-for-job-2
  annotations:
    pod-create.stage.kwok.x-k8s.io/delay: "20000"
    pod-complete.stage.kwok.x-k8s.io/delay: "20000"
    pod-init-container-completed.stage.kwok.x-k8s.io/delay: "20000"
    pod-init-container-running.stage.kwok.x-k8s.io/delay: "20000"
    pod-delete.stage.kwok.x-k8s.io/delay: "20000"
spec:
  template:
    spec:
      tolerations:
      - key: "kwok-controller/provider"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: job
        image: fake
      restartPolicy: Never
  backoffLimit: 4
```

On each stage I have the fields setting the default delay for 10 seconds
```
delay:
    durationMilliseconds: 10000
    durationFrom:
    expressionFrom: '.metadata.annotations["{STAGE-NAME}.stage.kwok.x-k8s.io/delay"]'
    jitterDurationMilliseconds: 10000
    jitterDurationFrom:
      expressionFrom: '.metadata.annotations["{STAGE-NAME}.stage.kwok.x-k8s.io/jitter-delay"]'
```

When I create the jobs, both of them progress trough their status simultaneously, however the second one should take double the time according the priority order for [.durationFrom](https://kwok.sigs.k8s.io/docs/user/stages-configuration/#how-delay-is-calculated). With this in mind, I would like to ask you if the way I'm using these annotations for configuring a delay individually for each pod is correct. And if not, is it possible to configure a individual delay for each pod?

Status of the jobs running
![image](https://github.com/user-attachments/assets/240cd7b4-246f-4977-a84b-21fb5eec2d0a)

**Reply by wzshiming** [reply]
The annotations needs to be in the pod (or pod template), not the job

``` yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test-pod-for-job
spec:
  template:
    spec:
      tolerations:
      - key: "kwok-controller/provider"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: job
        image: fake
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-pod-for-job-2
spec:
  template:
    metadata:
      annotations:
        pod-create.stage.kwok.x-k8s.io/delay: "20s"
        pod-complete.stage.kwok.x-k8s.io/delay: "20s"
        pod-init-container-completed.stage.kwok.x-k8s.io/delay: "20s"
        pod-init-container-running.stage.kwok.x-k8s.io/delay: "20s"
        pod-delete.stage.kwok.x-k8s.io/delay: "20s"
    spec:
      tolerations:
      - key: "kwok-controller/provider"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: job
        image: fake
      restartPolicy: Never
  backoffLimit: 4
```
