### DISCUSSION TITLE
Kwok default-scheduler doesn't respect "Topology Spread Constraints"

### DISCUSSION THREAD

**Discussion by kunZooberg** [kubernetes-sigs/kwok#573] [Q&A] [answered]
I found pods with "Topology Spread Constraints" below can be scheduled into same node in kwok
```yaml
        topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: appName
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
```
Repro:
1. Create deployment with topologySpreadConstraints above with 30 replicas.
2. Create nodes one by one
3. Found pods with above topologySpreadConstraints and same app label can be scheduled into same node.
Pod1:
![image](https://user-images.githubusercontent.com/52813547/236624283-eea7d249-45ad-4653-ac26-033fd6f6b370.png)
Pod2:
![image](https://user-images.githubusercontent.com/52813547/236624263-25f6b6b1-2879-4fae-a015-b10c12a49c6d.png)

**Comment by wzshiming** [comment, marked as answer]
https://github.com/kubernetes/kubernetes/blob/7f370d651ddef1106ad0d6fa8fd4e1e8a4bf8d44/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L379

I debugged and found that this was because the values of `matchNum` and `minMatchNum` were always equal, and giving `minDomains` a larger value would then cause `minMatchNum` to be set to 0.

``` yaml
        topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: appName
          maxSkew: 1
          minDomains: 5
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
```
