### ISSUE TITLE
kwok controller deployment shouldn't schedule onto a kwok node

### ISSUE THREAD

**Issue by njtran** [kubernetes-sigs/kwok#1147]
### What would you like to be added?

Currently I'm adding in a node affinity so that the kwok controller deployment doesn't schedule onto a kwok node here in Karpenter: https://github.com/kubernetes-sigs/karpenter/blob/main/hack/install-kwok.sh#L34-L40
```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kwok.x-k8s.io/node
                operator: DoesNotExist
```

I see the current deployment spec doesn't have this, https://github.com/kubernetes-sigs/kwok/blob/main/kustomize/kwok/deployment.yaml

Which means that I have to orchestrate patching this in my kustomize, when I think it's pretty normal to not want to schedule the pod that needs to run to a fake node. 

Happy to help add this in if it would be supported.

### Why is this needed?

Kwok controller pods shouldn't schedule onto a kwok node, since the controller wouldn't be able to run.
