### ISSUE TITLE
Vertical Pod Autoscaler in KWOK Cluster Fails to Adjust CPU Usage

### ISSUE THREAD

**Issue by network-charles** [kubernetes-sigs/kwok#1181]
### How to use it?

- [X] kwok
- [ ] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

When a vertical pod autoscaler is installed in a KWOK cluster, it doesn't react when a pod is deployed.

### What did you expect to happen?

After using the `Auto` mode in the VPA definition, I expected it to readjust the pod CPU to the most suitable value, however, it did nothing. Other VPA modes don't work either.

### How can we reproduce it (as minimally and precisely as possible)?

**deployment.yaml**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
```

**vpa.yaml**
```yaml
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-nginx
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       nginx
  updatePolicy:
    updateMode: "Auto"
```

**scale-using-vpa.demo**
```yaml
# Scale pod up & down using VPA

# Set up Cluster
kwokctl create cluster --enable-metrics-server --enable-crds=Metric --enable-crds=ClusterResourceUsage --enable-crds=ResourceUsage

# Apply metrics usage
kubectl apply -f https://github.com/kubernetes-sigs/kwok/releases/download/v0.6.0/metrics-usage.yaml

# Create a node
kwokctl scale node --replicas 1 --param '.allocatable.cpu="4000m"'

# Create deployment
kubectl apply -f deployment.yaml

# Install VPA
git clone https://github.com/kubernetes/autoscaler.git
cd autoscaler/vertical-pod-autoscaler/
./hack/vpa-up.sh
cd ..
cd ..

# Validating Successful VPA Deployment
kubectl get pods -n kube-system | grep vpa

# Deploy VPA
kubectl apply -f vpa.yaml

# Wait 30s
sleep 30

# Check CPU usage
kubectl top pod
```

### Kwok version

<details>

```console
$ kwok --version
kwok version v0.6.0 go1.22.3 (linux/amd64)

$ kwokctl --version
kwokctl version v0.6.0 go1.22.3 (linux/amd64)
```

</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux ip-172-31-45-84 6.5.0-1022-aws #22~22.04.1-Ubuntu SMP Fri Jun 14 16:31:00 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
</details>

**Comment by wzshiming** [comment]
Ah, this is a simulation cluster, can't run the container, you may need a following step to set up VPA

## admission-service.yaml 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: vpa-webhook
  namespace: kube-system
spec:
  ports:
    - port: 443
      targetPort: 8000
  externalName: host.docker.internal
```


``` bash
# Set up Cluster
kwokctl create cluster --enable-metrics-server --enable-crds=Metric --enable-crds=ClusterResourceUsage --enable-crds=ResourceUsage

# Apply metrics usage
kubectl apply -f https://github.com/kubernetes-sigs/kwok/releases/download/v0.6.0/metrics-usage.yaml

# Create a node
kwokctl scale node --replicas 1 --param '.allocatable.cpu="4000m"'


# Install VPA
git clone https://github.com/kubernetes/autoscaler.git

kubectl apply -f ./autoscaler/vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml
kubectl apply -f ./autoscaler/vertical-pod-autoscaler/deploy/vpa-rbac.yaml

cd autoscaler/vertical-pod-autoscaler/ && ./hack/vpa-up.sh
kubectl apply -f admission-service.yaml

# Execute on new terminal
cd autoscaler/vertical-pod-autoscaler/ && NAMESPACE=kube-system go run ./pkg/admission-controller --kubeconfig ~/.kube/config --client-ca-file ~/.kwok/clusters/kwok/pki/ca.crt --tls-cert-file  ~/.kwok/clusters/kwok/pki/admin.crt --tls-private-key  ~/.kwok/clusters/kwok/pki/admin.key
cd autoscaler/vertical-pod-autoscaler/ && NAMESPACE=kube-system go run ./pkg/recommender --kubeconfig ~/.kube/config
cd autoscaler/vertical-pod-autoscaler/ && NAMESPACE=kube-system go run ./pkg/updater --kubeconfig ~/.kube/config

```

**Comment by network-charles** [comment]
Thanks, I'll try it.

**Comment by wzshiming** [comment]
It seems to have reacted, Did you run all 3 processes?
``` bash
$ kubectl get pod -A 
NAMESPACE   NAME                     READY   STATUS    RESTARTS   AGE
default     nginx-6f999cfffb-dcvjq   1/1     Running   0          2m55s

$ kubectl get vpa 
NAME        MODE   CPU   MEM       PROVIDED   AGE
vpa-nginx   Auto   25m   262144k   True       3m24s
```

Or you can try the example that comes with vpa

``` 
autoscaler/vertical-pod-autoscaler/examples/hamster.yaml
autoscaler/vertical-pod-autoscaler/examples/redis.yaml
```

**Comment by network-charles** [comment]
I see where the issue came from, I ran the process commands in one new terminal. I decided to run 3 new terminals, one for each process and it worked.

**Comment by network-charles** [comment]
So, I just noticed that the VPA didn't update any pod requests in the deployment. I added a request value to the deployment.
**deployment.yaml**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
```
I waited for 17 minutes.
```bash
kubectl get pod 

NAME                    READY   STATUS    RESTARTS   AGE
nginx-77c678789-m8sp4   1/1     Running   0          17m
nginx-77c678789-nwn9r   1/1     Running   0          17m
```

**Comment by network-charles** [comment]
Ok, so I noticed that the issue was the below resource policy I added to the VPA manifest. (A referenced [discussion](https://discuss.kubernetes.io/t/kubernetes-vetical-pod-autoscaler-wont-recreate-pods/19760) on the kubernetes website with this same issue but no fix yet)
```yaml
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources: ["CPU"]
 ```
 
 After, removing it, the pods were recreated. However, the new requested CPU wasn't adjusted. The VPA suggested `25m` but the requested pod CPU still used `100m`
 ```bash
 kubectl get vpa
NAME        MODE   CPU   MEM       PROVIDED   AGE
vpa-nginx   Auto   25m   262144k   True       5m
```

```bash
kubectl get pod -o yaml | grep -i cpu

cpu: 100m
cpu: 100m
```
