### ISSUE TITLE
The `immediateNextStage` doesn't take any effect

### ISSUE THREAD

**Issue by danielsiwiec** [kubernetes-sigs/kwok#1226]
### How to use it?

- [X] kwok
- [ ] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

When applying a Stage with `immediateNextStage: true` after the pod has been created, the Stage transition happens after ~30 seconds, regardless of the flag being set or not

### What did you expect to happen?

The Stage transition should happen immediatelly.

### How can we reproduce it (as minimally and precisely as possible)?

Start up kwok:
```shell
docker run --rm -it -p 8080:8080 registry.k8s.io/kwok/cluster:v0.6.0-k8s.v1.30.2 --enable-crds=Stage
```
Create a default node:
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    kwok.x-k8s.io/node: fake
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: kwok-node-0
    kubernetes.io/os: linux
    kubernetes.io/role: agent
    node-role.kubernetes.io/agent: ""
    type: kwok
  name: kwok-node-0
status:
  allocatable:
    cpu: 32
    memory: 256Gi
    pods: 512
  capacity:
    cpu: 32
    memory: 256Gi
    pods: 512
  nodeInfo:
    architecture: amd64
    bootID: ""
    containerRuntimeVersion: ""
    kernelVersion: ""
    kubeProxyVersion: fake
    kubeletVersion: fake
    machineID: ""
    operatingSystem: linux
    osImage: ""
    systemUUID: ""
  phase: Running
EOF
```

Create default stages:
```
kubectl apply -f kustomize/stage/pod/fast
```

Install OpenTelemetry Demo stack:
```
helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
helm install otel open-telemetry/opentelemetry-demo --namespace demo --create-namespace
```

Apply Stage:
```
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: demo-pod-restart
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
      - key: '.metadata.name | if type == "string" and contains("accounting") then "True" else "False" end'
        operator: 'In'
        values:
          - 'True'
  immediateNextStage: true
  next:
    statusTemplate: |
      {{ $now := Now }}
      phase: Running
      conditions:
        - type: PodReadyToStartContainers
          status: 'True'
          lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
        - type: Initialized
          status: 'True'
          lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
        - type: Ready
          status: 'True'
          lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
        - type: ContainersReady
          status: 'True'
          lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
        - type: PodScheduled
          status: 'True'
          lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
      startTime: {{ $now | Quote }}
      containerStatuses:
      {{ range $index, $item := .spec.containers }}
        - name: {{ $item.name | Quote }}
          state:
            running:
              startedAt: {{ $now | Quote }}
          lastState:
            terminated:
              exitCode: 137
              reason: Error
              startedAt: {{ $now | Quote }}
              finishedAt: {{ $now | Quote }}
          ready: true
          restartCount: 395
          image: {{ $item.image | Quote }}
          started: true
      {{ end }}
```

### Kwok version

registry.k8s.io/kwok/cluster:v0.6.0-k8s.v1.30.2

### OS version

Darwin Dans-MBP.nv.charter.com 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030 arm64

**Comment by wzshiming** [comment]
Ahh, it would be best if you did not use ImmediateNextStage.
and matchExpressions does not support CEL yet it only supports JQ, so this stage should not be in effect.
Can you tell me what you're doing? Maybe I can give you the exact steps.

**Comment by danielsiwiec** [comment]
thanks @wzshiming ! at a high level, what I'm doing, is using kwok in a test suite, simulating a real kubernetes cluster. in the test suite, kwok is already provisioned, along with a demo Helm chart (in our case OpenTelemetry demo). individual tests manipulate the kwok cluster in various way. for instance - one test is setting up a pod into a failing state.

so, in essence, I'm trying to apply a state transition instantly, after the helm char has already been installed. is there a better way of doing this?

**Comment by wzshiming** [comment]
I understand you want to simulate a pod failure, here is an example.

Stage: https://github.com/kubernetes-sigs/kwok/blob/main/kustomize/stage/pod/chaos/pod-init-container-running-failed.yaml

Usage case: https://github.com/NVIDIA/knavigator/blob/5c27d87ab165ff6aaf5b145df9564442a764d660/resources/templates/k8s/failed-job.yml#L28

**Comment by danielsiwiec** [comment]
I think my problem is when I define the stage _after_ I create the resources. Here's my sequence:
- I start up kwok
- I add a node
- I install the Helm chart
- I apply the `Stage`
- I see the stage applied after ~30 seconds

Here's my stage, for reference:

```yaml
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-restarting
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - key: '.metadata.labels["app.kubernetes.io/component"]'
      operator: 'In'
      values:
      - 'accountingservice'
  next:
    statusTemplate: |
      {{ $now := Now }}
      phase: Running
      conditions:
        - type: PodReadyToStartContainers
          status: 'True'
          lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
        - type: Initialized
          status: 'True'
          lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
        - type: Ready
          status: 'True'
          lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
        - type: ContainersReady
          status: 'True'
          lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
        - type: PodScheduled
          status: 'True'
          lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
      startTime: {{ $now | Quote }}
      containerStatuses:
      {{ range $index, $item := .spec.containers }}
        - name: {{ $item.name | Quote }}
          state:
            running:
              startedAt: {{ $now | Quote }}
          lastState:
            terminated:
              exitCode: 137
              reason: Error
              startedAt: {{ $now | Quote }}
              finishedAt: {{ $now | Quote }}
          ready: true
          restartCount: 395
          image: {{ $item.image | Quote }}
          started: true
      {{ end }}
```

**Comment by wzshiming** [comment]
Oh I see, you want to actively trigger a Stage, it just need to add a specific annotation/label match for Stage, as the following

https://github.com/kubernetes-sigs/kwok/blob/0e9df27554f63be64168595e6bb28d5c03282838/kustomize/stage/pod/chaos/pod-init-container-running-failed.yaml#L10-L14


So you can do it like this

``` yaml
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-restarting
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - key: '.metadata.labels["restart.stage.kwok"]'
      operator: 'In'
      values:
      - 'true'
  next:
    weight: 1
    statusTemplate: |
      {{ $now := Now }}
      phase: Running
      conditions:
        - type: PodReadyToStartContainers
          status: 'True'
          lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
        - type: Initialized
          status: 'True'
          lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
        - type: Ready
          status: 'True'
          lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
        - type: ContainersReady
          status: 'True'
          lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
      startTime: {{ $now | Quote }}
      containerStatuses:
      {{ range $index, $item := .spec.containers }}
        - name: {{ $item.name | Quote }}
          state:
            running:
              startedAt: {{ $now | Quote }}
          lastState:
            terminated:
              exitCode: 137
              reason: Error
              startedAt: {{ $now | Quote }}
              finishedAt: {{ $now | Quote }}
          ready: true
          restartCount: 395
          image: {{ $item.image | Quote }}
          started: true
      {{ end }}
```

and add it to the pod when needed

``` bash
kubectl patch pod pod-xxxx \
  --type=json \
  -p='[{"op":"add","path":"/metadata/labels","value":{"restart.stage.kwok":"true"}}]'
```
