### ISSUE TITLE
Add manage pod with selector

### ISSUE THREAD

**Issue by anson627** [kubernetes-sigs/kwok#1401]
### What would you like to be added?

A webhook to call kwok controller/server and patch pods that are created with labels (e.g. `app: fake-pod`) and not in certain namespaces (e.g. `kube-system`), with node affinity and tolerations like
```
affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - kwok
      tolerations:
      - key: "kwok.x-k8s.io/node"
        operator: "Exists"
        effect: "NoSchedule"
```

### Why is this needed?

To make kwok work with addons like kuberay, for example, RayJob CRD does not allow to customize node affinity and tolerations, so it's not possible to schedule job submitter pod to kwok node and change its behavior  via stage upon creation
