### ISSUE TITLE
[kwok] Provide Kubelet metrics

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#199]
### What would you like to be added?

- [ ] /metrics
- [ ] /metrics/cadvisor
- [ ] /metrics/resource
- [ ] /metrics/probes

#### Provides generic functions that enable it to simulate data for any indicator.

``` yaml
kind: Metric
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: node-name
spec:
  # I'm not sure if there is a way to configure the `metric-server` to change the path of the node metrics collection
  path: "/metrics/nodes/{{ .metadata.name }}"
  metrics:
    - name: kubelet_node_name
      help: [ALPHA] The node's name. The count is always 1.
      kind: gauge
      labels:
        - name: node
          value: 'node.metadata.name'
      value: '1'
    - name: kubelet_started_containers_total
      # For special cases, we can also consider providing special functions to provide data,
      # such as this number of containers started.
      help: [ALPHA] Cumulative number of containers started
      kind: counter
      value: 'startedContainersTotal( node.metadata.name )'
    - name: kubelet_pleg_relist_duration_seconds
      help: [ALPHA] Duration in seconds of a single pod list and pod events list call.
      kind: histogram
      buckets:
        - le: 0.005
          value: '( unixSecond(now()) - unixSecond(node.metadata.creationTimestamp) ) / 10'
        - le: 0.01
          value: '( unixSecond(now()) - unixSecond(node.metadata.creationTimestamp) ) / 10'
        - le: 0.025
          value: '( unixSecond(now()) - unixSecond(node.metadata.creationTimestamp) ) / 9'
        - le: 0.05
          value: '( unixSecond(now()) - unixSecond(node.metadata.creationTimestamp) ) / 9'
        - le: 0.1
          value: '( unixSecond(now()) - unixSecond(node.metadata.creationTimestamp) ) / 8'
        - le: 0.25
          value: '( unixSecond(now()) - unixSecond(node.metadata.creationTimestamp) ) / 8'
        - le: 0.5
          value: '( unixSecond(now()) - unixSecond(node.metadata.creationTimestamp) ) / 7'
        - le: 1
          value: '( unixSecond(now()) - unixSecond(node.metadata.creationTimestamp) ) / 7'
        - le: 2.5
          value: '( unixSecond(now()) - unixSecond(node.metadata.creationTimestamp) ) / 6'
        - le: 5
          value: '( unixSecond(now()) - unixSecond(node.metadata.creationTimestamp) ) / 6'
        - le: 10
          value: '( unixSecond(now()) - unixSecond(node.metadata.creationTimestamp) ) / 5'
        - le: +Inf
          value: '( unixSecond(now()) - unixSecond(node.metadata.creationTimestamp) ) / 4'
```

Describing values using [CEL expressions](https://github.com/google/cel-go)

### Why is this needed?

https://github.com/kubernetes-sigs/kwok/discussions/159#discussioncomment-4632899
