### ISSUE TITLE
[kwok] Provided service for `logs`

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#217]
``` yaml
# Match pods
kind: ClusterLogs
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: cluster-logs-rules
spec:
  selector:
    matchNamespaces:
      - podNamespace
    matchNames:
      - podName
  logs: []
--- 
# Just for a Pod
kind: Logs
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: podName
  namespace: podNamespace
spec:
  logs:
    - containers:
        - containerName

      # The first response is the contents of the logsFile
      # TODO: I'm not sure how to do support the --since-time, --since, --tail, --previous
      logsFile: /tmp/kwok.log

      # Follow up if true
      follow: true

```

/kind feature
