### ISSUE TITLE
[kwok] Provided service for `exec`

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#236]
``` yaml
# Match pods
kind: ClusterExec
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: cluster-exec-rules
spec:
  selector:
    matchNamespaces:
      - podNamespace
    matchNames:
      - podName
  execs: []
--- 
# Just for a Pod
kind: Exec
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: podName
  namespace: podNamespace
spec:
  execs:
    - containers:
        - containerName
      local:
        workDir: "/workdir"
        envs:
          - <envkey>=<envvalue>

      # Maybe support ssh in future
      # ssh:
      #   address:
      #  # todo
```

/kind feature
