### ISSUE TITLE
[kwok] Provided service for `attach`

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#237]
``` yaml
# Match pods
kind: ClusterAttach
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: cluster-attach-rules
spec:
  selector:
    matchNamespaces:
      - podNamespace
    matchNames:
      - podName
  attaches: []
--- 
# Just for a Pod
kind: Attach
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: podName
  namespace: podNamespace
spec:
  attaches:
    - containers:
        - containerName
      
      logsFile: /tmp/kwok.log

```

/kind feature
