### ISSUE TITLE
[kwokctl] Support for detecting the latest k8s version

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#364]
### What would you like to be added?

- Maintain supported k8s releases for each kwokctl release on kwok.sigs.k8s.io
- kwokctl gets its supported releases when first used

``` yaml
kind: KubectlStableOptions
apiVersion: kwok.x-k8s.io
rules:
  - match: # match the version of kubectl
      - tag: 'v0.1.0'
        os: 'linux' # optinal ( darwin | linux | windows )
        arch: 'amd64' # optinal ( amd64 | arm64 )
        runtime: 'binary' # optinal ( binary | docker | nerdctl | kind )
    options: # instand of kubectl options
      etcdVersion: v1.x.y
      kubeVersion: v1.x.y
      prometheusVersion: v1.x.y
```

Adding the command `kwokctl config init` will fetch the online `KubectlStableOptions` and match it to its own options and create `~/.kwok/kwok.yaml`

### Why is this needed?

- Improve user experience
- No need to follow the release of k8s
