### ISSUE TITLE
[kwok] Have a version configuration to organize the parameters

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#4]
> Do we need to define a configuration for kwok?

I'd like to have a version configuration to organize the parameters. It's a local file, not configMap/CRD, just like [scheduler config](https://kubernetes.io/docs/reference/scheduling/config/).

But defining CLI args is a good start.

_Originally posted by @Huang-Wei in https://github.com/kubernetes-sigs/kwok/pull/1#discussion_r935127887_

**Comment by wzshiming** [comment]
``` yaml
# ~/.kwok/kwok.yml
kind: KwokConfiguration
apiVersion: kwok.x-k8s.io/v1alpha1
spec:
  cidr: ""
  disregardStatusWithAnnotationSelector: ""
  disregardStatusWithLabelSelector: ""
  manageAllNodes: false
  manageNodesWithAnnotationSelector: ""
  manageNodesWithLabelSelector: ""
  nodeIP: ""
```

``` yaml
# ~/.kwok/kwokctl.yml
kind: KwokctlConfiguration
apiVersion: kwok.x-k8s.io/v1alpha1
spec:
  workdir: ""
  kubeApiserverPort: 0
  runtime: ""
  prometheusPort: 0
  kwokVersion: ""
  kubeVersion: ""
  etcdVersion: ""
  prometheusVersion: ""
  securePort: false
  quietPull: false
  kubeImagePrefix: ""
  etcdImagePrefix: ""
  kwokImagePrefix: ""
  prometheusImagePrefix: ""
  etcdImage: ""
  kubeApiserverImage: ""
  kubeControllerManagerImage: ""
  kubeSchedulerImage: ""
  kwokControllerImage: ""
  prometheusImage: ""
  kindNodeImagePrefix: ""
  kindNodeImage: ""
  kubeBinaryPrefix: ""
  kubeApiserverBinary: ""
  kubeControllerManagerBinary: ""
  kubeSchedulerBinary: ""
  kubectlBinary: ""
  etcdBinaryPrefix: ""
  etcdBinary: ""
  etcdBinaryTar: ""
  kwokBinaryPrefix: ""
  kwokControllerBinary: ""
  prometheusBinaryPrefix: ""
  prometheusBinary: ""
  prometheusBinaryTar: ""
  mode: ""
  kubeFeatureGates: ""
  kubeRuntimeConfig: ""
  kubeAuditPolicy: ""
  kubeAuthorization: ""
```

Pod lifecycle simulation configuration #67
