### ISSUE TITLE
[kwok] Pod lifecycle simulation

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#67]
This is just a preliminary design

## Goals
- Support simulate the pod's real behavior as much as possible
- Flexible and configurable
- Present some templates:
  - Up and running quickly
  - Simulates realistic normal/abnormal behavior

## Design 1

<details>

``` yaml
kind: Scenario
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: scenario-0
spec:
  selector:
    matchLabels:
      app: demo
  stages:
  - kind: Duration
    delay: 5s
    jitter: 0.2

  - kind: Switch
    cases:
    - weight: 9
      stages: 
      - kind: PresetStatus
        template: PullImage
    - weight: 1
      stages: 
      - kind: PresetStatus
        template: FailedPullImage
      - kind: GoToBegin

  - kind: Duration
    delay: 1s

  - kind: PresetStatus
    template: Creating

  - kind: Duration
    delay: 1s
    jitter: 0.1

  - kind: PresetStatus
    template: NotReady

  - kind: Duration
    delay: 1s
    jitter: 0.1

  - kind: Switch
    cases:
    - weight: 20
      stages: 
      - kind: PresetStatus
        template: Ready
      - kind: End

    - weight: 5
      stages: 
      - kind: PresetStatus
        template: Failed
      - kind: End

    - weight: 5
      - kind: PresetStatus
        template: Restart
      - kind: GoToBegin

```

</details>

## Design 2

``` yaml
kind: Stage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: pod-create
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
      - key: '.metadata.deletionTimestamp'
        operator: 'DoesNotExist'
      - key: '.status.podIP'
        operator: 'DoesNotExist'
  weight: 1
  delay:
    durationSeconds: 1
  next:
    event:
      type: Normal
      reason: Created
      message: Created container
    finalizers:
      add:
        - value: 'kwok.x-k8s.io/fake'
    statusTemplate: |
      {{ $now := Now }}
      conditions:
      {{ if .spec.initContainers }}
        - lastProbeTime: null
          lastTransitionTime: '{{ $now }}'
          message: 'containers with incomplete status: [{{ range .spec.initContainers }} {{ .name }} {{ end }}]'
          reason: ContainersNotInitialized
          status: "False"
          type: Initialized
      {{ else }}
        - lastProbeTime: null
          lastTransitionTime: '{{ $now }}'
          status: "True"
          type: Initialized
      {{ end }}
        - lastProbeTime: null
          lastTransitionTime: '{{ $now }}'
          message: 'containers with unready status: [{{ range .spec.containers }} {{ .name }} {{ end }}]'
          reason: ContainersNotReady
          status: "False"
          type: Ready
        - lastProbeTime: null
          lastTransitionTime: '{{ $now }}'
          message: 'containers with unready status: [{{ range .spec.containers }} {{ .name }} {{ end }}]'
          reason: ContainersNotReady
          status: "False"
          type: ContainersReady
      {{ range .spec.readinessGates }}
        - lastTransitionTime: {{ $now }}
          status: "True"
          type: {{ .conditionType }}
      {{ end }}
      {{ if .spec.initContainers }}
      initContainerStatuses:
        {{ range .spec.initContainers }}
        - image: {{ .image }}
          name: {{ .name }}
          ready: false
          restartCount: 0
          started: false
          state:
            waiting:
              reason: PodInitializing
        {{ end }}
      containerStatuses:
        {{ range .spec.containers }}
        - image: {{ .image }}
          name: {{ .name }}
          ready: false
          restartCount: 0
          started: false
          state:
            waiting:
              reason: PodInitializing
        {{ end }}
      {{ else }}
      containerStatuses:
        {{ range .spec.containers }}
        - image: {{ .image }}
          name: {{ .name }}
          ready: false
          restartCount: 0
          started: false
          state:
            waiting:
              reason: ContainerCreating
        {{ end }}
      {{ end }}
      hostIP: {{ with .status.hostIP }} {{ . }} {{ else }} {{ NodeIP }} {{ end }}
      podIP: {{ with .status.podIP }} {{ . }} {{ else }} {{ PodIP }} {{ end }}
      phase: Pending
---
kind: Stage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: pod-init-container-running
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
      - key: '.metadata.deletionTimestamp'
        operator: 'DoesNotExist'
      - key: '.status.phase'
        operator: 'In'
        values:
          - 'Pending'
      - key: '.status.conditions.[] | select( .type == "Initialized" ) | .status'
        operator: 'NotIn'
        values:
          - 'True'
      - key: '.status.initContainerStatuses.[].state.waiting.reason'
        operator: 'Exists'
  weight: 1
  delay:
    durationSeconds: 5
  next:
    statusTemplate: |
      {{ $now := Now }}
      {{ $root := . }}
      initContainerStatuses:
        {{ range $index, $item := .spec.initContainers }}
        {{ $origin := index $root.status.initContainerStatuses $index }}
        - image: {{ $item.image }}
          name: {{ $item.name }}
          ready: true
          restartCount: 0
          started: true
          state:
            running:
              startedAt: '{{ $now }}'
        {{ end }}
---
kind: Stage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: pod-init-container-completed
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
      - key: '.metadata.deletionTimestamp'
        operator: 'DoesNotExist'
      - key: '.status.phase'
        operator: 'In'
        values:
          - 'Pending'
      - key: '.status.conditions.[] | select( .type == "Initialized" ) | .status'
        operator: 'NotIn'
        values:
          - 'True'
      - key: '.status.initContainerStatuses.[].state.running.startedAt'
        operator: 'Exists'
  weight: 1
  delay:
    durationSeconds: 5
  next:
    statusTemplate: |
      {{ $now := Now }}
      {{ $root := . }}
      conditions:
        - lastProbeTime: null
          lastTransitionTime: '{{ $now }}'
          status: "True"
          type: Initialized
      initContainerStatuses:
        {{ range $index, $item := .spec.initContainers }}
        {{ $origin := index $root.status.initContainerStatuses $index }}
        - image: {{ $item.image }}
          name: {{ $item.name }}
          ready: true
          restartCount: 0
          started: false
          state:
            terminated:
              exitCode: 0
              finishedAt: '{{ $now }}'
              reason: Completed
              startedAt: '{{ $now }}'
        {{ end }}
      containerStatuses:
        {{ range .spec.containers }}
        - image: {{ .image }}
          name: {{ .name }}
          ready: false
          restartCount: 0
          started: false
          state:
            waiting:
              reason: ContainerCreating
        {{ end }}
---
kind: Stage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: pod-ready
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
      - key: '.metadata.deletionTimestamp'
        operator: 'DoesNotExist'
      - key: '.status.phase'
        operator: 'In'
        values:
          - 'Pending'
      - key: '.status.conditions.[] | select( .type == "Initialized" ) | .status'
        operator: 'In'
        values:
          - 'True'
      - key: '.status.conditions.[] | select( .type == "ContainersReady" ) | .status'
        operator: 'NotIn'
        values:
          - 'True'
  weight: 1
  delay:
    durationSeconds: 10
  next:
    delete: false
    statusTemplate: |
      {{ $now := Now }}
      {{ $root := . }}
      conditions:
        - lastProbeTime: null
          lastTransitionTime: '{{ $now }}'
          message: ''
          reason: ''
          status: "True"
          type: Ready
        - lastProbeTime: null
          lastTransitionTime: '{{ $now }}'
          message: ''
          reason: ''
          status: "True"
          type: ContainersReady
      containerStatuses:
        {{ range $index, $item := .spec.containers }}
        {{ $origin := index $root.status.containerStatuses $index }}
        - image: {{ $item.image }}
          name: {{ $item.name }}
          ready: true
          restartCount: 0
          started: true
          state:
            running:
              startedAt: '{{ $now }}'
        {{ end }}
      phase: Running
---
kind: Stage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: pod-completed-for-job
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
      - key: '.metadata.deletionTimestamp'
        operator: 'DoesNotExist'
      - key: '.status.phase'
        operator: 'In'
        values:
          - 'Running'
      - key: '.status.conditions.[] | select( .type == "Ready" ) | .status'
        operator: 'In'
        values:
          - 'True'
      - key: '.metadata.ownerReferences.[].kind'
        operator: 'In'
        values:
          - 'Job'
  weight: 1
  delay:
    durationSeconds: 10
  next:
    delete: false
    statusTemplate: |
      {{ $now := Now }}
      {{ $root := . }}
      containerStatuses:
        {{ range $index, $item := .spec.containers }}
        {{ $origin := index $root.status.containerStatuses $index }}
        - image: {{ $item.image }}
          name: {{ $item.name }}
          ready: true
          restartCount: 0
          started: false
          state:
            terminated:
              exitCode: 0
              finishedAt: '{{ $now }}'
              reason: Completed
              startedAt: '{{ $now }}'
        {{ end }}
      phase: Succeeded
---
kind: Stage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: pod-remove-finalizer
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
      - key: '.metadata.deletionTimestamp'
        operator: 'Exists'
      - key: '.metadata.finalizers'
        operator: 'In'
        values:
          - 'kwok.x-k8s.io/fake'
  weight: 1
  delay:
    durationSeconds: 1
  next:
    finalizers:
      remove:
        - value: 'kwok.x-k8s.io/fake'
    event:
      type: Normal
      reason: Killing
      message: Stopping container
---
kind: Stage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: pod-delete
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
      - key: '.metadata.deletionTimestamp'
        operator: 'Exists'
      - key: '.metadata.finalizers'
        operator: 'DoesNotExist'
  weight: 1
  delay:
    durationSeconds: 1
    jitterDurationSecondsFrom:
      expressionFrom: '.metadata.deletionTimestamp'
  next:
    delete: true
```

``` golang
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Stage is an API that describes the staged change of a resource
type Stage struct {
	metav1.TypeMeta `json:",inline"`
	// Standard list metadata.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// Spec holds information about the request being evaluated.
	Spec StageSpec `json:"spec,omitempty"`
}

// StageSpec defines the specification for Stage.
type StageSpec struct {
	// ResourceRef specifies the Kind and version of the resource.
	ResourceRef StageResourceRef `json:"resourceRef"`
	// Selector specifies the stags will be applied to the selected resource.
	Selector *StageSelector `json:"selector,omitempty"`
	// Weight means the current stage, in case of multiple stages,
	// a random stage will be matched as the next stage based on the weight.
	Weight *int `json:"weight,omitempty"`
	// Delay means there is a delay in this stage.
	Delay *StageDelay `json:"delay,omitempty"`
	// Next indicates that this stage will be moved to.
	Next StageNext `json:"next"`
}

// StageResourceRef specifies the kind and version of the resource.
type StageResourceRef struct {
	// APIGroup of the referent.
	APIGroup *string `json:"apiGroup,omitempty"`
	// Kind of the referent.
	Kind string `json:"kind"`
}

// StageDelay describes the delay time before going to next.
type StageDelay struct {
	// DurationSeconds indicates the stage delay time (in seconds).
	// If JitterDurationSeconds is less than DurationSeconds, then JitterDurationSeconds is used.
	DurationSeconds int `json:"durationSeconds"`
	// DurationSecondsFrom is the expression used to get the value.
	// If it is a time.Time type, getting the value will be minus now() to get DurationSeconds
	// If it is a string type, the value get will be parsed by time.ParseDuration.
	DurationSecondsFrom *ExpressionFromSource `json:"durationSecondsFrom,omitempty"`

	// JitterDurationSeconds is the duration plus an additional amount chosen uniformly
	// at random from the interval between `durationSeconds` and `jitterDurationSeconds`.
	JitterDurationSeconds *int `json:"jitterDurationSeconds,omitempty"`
	// JitterDurationSecondsFrom is the expression used to get the value.
	// If it is a time.Time type, getting the value will be minus now() to get JitterDurationSeconds
	// If it is a string type, the value get will be parsed by time.ParseDuration.
	JitterDurationSecondsFrom *ExpressionFromSource `json:"jitterDurationSecondsFrom,omitempty"`
}

// StageNext describes a stage will be moved to.
type StageNext struct {
	// Event means that an event will be sent.
	Event *StageEvent `json:"event,omitempty"`
	// Finalizers means that finalizers will be modified.
	Finalizers *StageFinalizers `json:"finalizers,omitempty"`
	// Delete means that the resource will be deleted if true.
	Delete bool `json:"delete,omitempty"`
	// StatusTemplate indicates the template for modifying the status of the resource in the next.
	StatusTemplate string `json:"statusTemplate,omitempty"`
}

// StageFinalizers describes the modifications in the finalizers of a resource.
type StageFinalizers struct {
	// Add means that the Finalizers will be added to the resource.
	Add []FinalizerItem `json:"add,omitempty"`
	// Remove means that the Finalizers will be removed from the resource.
	Remove []FinalizerItem `json:"remove,omitempty"`
	// Empty means that the Finalizers for that resource will be emptied.
	Empty bool `json:"empty,omitempty"`
}

// FinalizerItem  describes the one of the finalizers.
type FinalizerItem struct {
	Value string `json:"value,omitempty"`
}

// StageEvent describes one event in the Kubernetes.
type StageEvent struct {
	// Type is the type of this event (Normal, Warning), It is machine-readable.
	Type string `json:"type,omitempty"`
	// Reason is why the action was taken. It is human-readable.
	Reason string `json:"reason,omitempty"`
	// Message is a human-readable description of the status of this operation.
	Message string `json:"message,omitempty"`
}

// StageSelector is a resource selector. the result of matchLabels and matchAnnotations and
// matchExpressions are ANDed. An empty resource selector matches all objects. A null
// resource selector matches no objects.
type StageSelector struct {
	// MatchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
	// map is equivalent to an element of matchExpressions, whose key field is ".metadata.labels[key]", the
	// operator is "In", and the values array contains only "value". The requirements are ANDed.
	MatchLabels map[string]string `json:"matchLabels,omitempty"`
	// MatchAnnotations is a map of {key,value} pairs. A single {key,value} in the matchAnnotations
	// map is equivalent to an element of matchExpressions, whose key field is ".metadata.annotations[key]", the
	// operator is "In", and the values array contains only "value". The requirements are ANDed.
	MatchAnnotations map[string]string `json:"matchAnnotations,omitempty"`
	// MatchExpressions is a list of label selector requirements. The requirements are ANDed.
	MatchExpressions []SelectorRequirement `json:"matchExpressions,omitempty"`
}

// SelectorRequirement is a resource selector requirement is a selector that contains values, a key,
// and an operator that relates the key and values.
type SelectorRequirement struct {
	// The name of the scope that the selector applies to.
	Key string `json:"key"`
	// Represents a scope's relationship to a set of values.
	Operator SelectorOperator `json:"operator"`
	// An array of string values.
	// If the operator is In, NotIn, Intersection or NotIntersection, the values array must be non-empty.
	// If the operator is Exists or DoesNotExist, the values array must be empty.
	Values []string `json:"values,omitempty"`
}

// SelectorOperator is a label selector operator is the set of operators that can be used in a selector requirement.
type SelectorOperator string

var (
	SelectorOpIn           SelectorOperator = "In"
	SelectorOpNotIn        SelectorOperator = "NotIn"
	SelectorOpExists       SelectorOperator = "Exists"
	SelectorOpDoesNotExist SelectorOperator = "DoesNotExist"
)

// ExpressionFromSource represents a source for the value of a from.
type ExpressionFromSource struct {
	// ExpressionFrom is the expression used to get the value.
	ExpressionFrom string `json:"expressionFrom,omitempty"`
}
```

**Comment by nagygergo** [comment]
In general looks good to me.
How does this select which scenario applies to which pods? Maybe:
```yaml
selector:
   matchLabels:
      app: demo
```

Also, what happens when multiple scenarios are matching the same pod?
I think it would be good if kwok would select one randomly in that case.

How will the kwok store the current step that the pod is in?
Could additional annotations implemented, like:
`kwok.x-k8s.io/scenario: scenario-0`
`kwok.x-k8s.io/scenario-stage: 1`
