### ISSUE TITLE
Provide /metrics/resource

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#671]
``` bash
kubectl get --raw "/api/v1/nodes/kind-control-plane/proxy/metrics/resource"
```

``` yaml
kind: Metric
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: fake-node-1
spec:
  path: "/metrics/resource/nodes/fake-node"
  metrics:
  - name: container_cpu_usage_seconds_total
    dimension: container
    help: "[ALPHA] Cumulative cpu time consumed by the container in core-seconds"
    kind: counter
    labels:
    - name: container
      value: 'container.name'
    - name: namespace
      value: 'pod.metadata.namespace'
    - name: pod
      value: 'pod.metadata.name'
    value: 'pod.SinceSecond() / 100.0'
  - name: container_memory_working_set_bytes
    dimension: container
    help: "[ALPHA] Current working set of the container in bytes"
    kind: gauge
    labels:
    - name: container
      value: 'container.name'
    - name: namespace
      value: 'pod.metadata.namespace'
    - name: pod
      value: 'pod.metadata.name'
    value: '1000000.0 * (1.0 + Rand())'
  - name: container_start_time_seconds
    dimension: container
    help: "[ALPHA] Start time of the container since unix epoch in seconds"
    kind: gauge
    labels:
    - name: container
      value: 'container.name'
    - name: namespace
      value: 'pod.metadata.namespace'
    - name: pod
      value: 'pod.metadata.name'
    value: 'pod.status.startTime.UnixSecond() - pod.metadata.creationTimestamp.UnixSecond()'
  - name: pod_cpu_usage_seconds_total
    dimension: pod
    help: "[ALPHA] Cumulative cpu time consumed by the pod in core-seconds"
    kind: counter
    labels:
    - name: namespace
      value: 'pod.metadata.namespace'
    - name: pod
      value: 'pod.metadata.name'
    value: 'pod.SinceSecond() / 100.0'
  - name: pod_memory_working_set_bytes
    dimension: pod
    help: "[ALPHA] Current working set of the pod in bytes"
    kind: gauge
    labels:
    - name: namespace
      value: 'pod.metadata.namespace'
    - name: pod
      value: 'pod.metadata.name'
    value: '1000000.0 * (1.0 + Rand())'
  - name: node_cpu_usage_seconds_total
    dimension: node
    help: "[ALPHA] Cumulative cpu time consumed by the node in core-seconds"
    kind: counter
    value: '1.0 + node.SinceSecond() / 10.0'
  - name: node_memory_working_set_bytes
    dimension: node
    help: "[ALPHA] Current working set of the node in bytes"
    kind: gauge
    value: '10000000.0 * (1.0 + Rand())'
  - name: scrape_error
    dimension: node
    help: "[ALPHA] 1 if there was an error while getting metrics from the node, 0 otherwise"
    kind: gauge
    value: '0'

```

<details><summary>Details</summary>
<p>

```
# HELP container_cpu_usage_seconds_total [ALPHA] Cumulative cpu time consumed by the container in core-seconds
# TYPE container_cpu_usage_seconds_total counter
container_cpu_usage_seconds_total{container="coredns",namespace="kube-system",pod="coredns-5d78c9869d-9dklc"} 1.254857 1687335071477
container_cpu_usage_seconds_total{container="coredns",namespace="kube-system",pod="coredns-5d78c9869d-bp5pq"} 1.169323 1687335086760
container_cpu_usage_seconds_total{container="etcd",namespace="kube-system",pod="etcd-kind-control-plane"} 13.124293 1687335070515
container_cpu_usage_seconds_total{container="kindnet-cni",namespace="kube-system",pod="kindnet-d6594"} 1.104116 1687335087391
container_cpu_usage_seconds_total{container="kube-apiserver",namespace="kube-system",pod="kube-apiserver-kind-control-plane"} 30.85694 1687335084344
container_cpu_usage_seconds_total{container="kube-controller-manager",namespace="kube-system",pod="kube-controller-manager-kind-control-plane"} 10.121293 1687335086617
container_cpu_usage_seconds_total{container="kube-proxy",namespace="kube-system",pod="kube-proxy-nsk4c"} 1.105087 1687335078555
container_cpu_usage_seconds_total{container="kube-scheduler",namespace="kube-system",pod="kube-scheduler-kind-control-plane"} 4.175869 1687335086329
container_cpu_usage_seconds_total{container="local-path-provisioner",namespace="local-path-storage",pod="local-path-provisioner-6bc4bddd6b-wq2jp"} 0.676889 1687335080585
# HELP container_memory_working_set_bytes [ALPHA] Current working set of the container in bytes
# TYPE container_memory_working_set_bytes gauge
container_memory_working_set_bytes{container="coredns",namespace="kube-system",pod="coredns-5d78c9869d-9dklc"} 1.3021184e+07 1687335071477
container_memory_working_set_bytes{container="coredns",namespace="kube-system",pod="coredns-5d78c9869d-bp5pq"} 1.3193216e+07 1687335086760
container_memory_working_set_bytes{container="etcd",namespace="kube-system",pod="etcd-kind-control-plane"} 2.9208576e+07 1687335070515
container_memory_working_set_bytes{container="kindnet-cni",namespace="kube-system",pod="kindnet-d6594"} 7.913472e+06 1687335087391
container_memory_working_set_bytes{container="kube-apiserver",namespace="kube-system",pod="kube-apiserver-kind-control-plane"} 2.32316928e+08 1687335084344
container_memory_working_set_bytes{container="kube-controller-manager",namespace="kube-system",pod="kube-controller-manager-kind-control-plane"} 4.1857024e+07 1687335086617
container_memory_working_set_bytes{container="kube-proxy",namespace="kube-system",pod="kube-proxy-nsk4c"} 1.5122432e+07 1687335078555
container_memory_working_set_bytes{container="kube-scheduler",namespace="kube-system",pod="kube-scheduler-kind-control-plane"} 2.1479424e+07 1687335086329
container_memory_working_set_bytes{container="local-path-provisioner",namespace="local-path-storage",pod="local-path-provisioner-6bc4bddd6b-wq2jp"} 9.076736e+06 1687335080585
# HELP container_start_time_seconds [ALPHA] Start time of the container since unix epoch in seconds
# TYPE container_start_time_seconds gauge
container_start_time_seconds{container="coredns",namespace="kube-system",pod="coredns-5d78c9869d-9dklc"} 1.6873346590242062e+09 1687334659024
container_start_time_seconds{container="coredns",namespace="kube-system",pod="coredns-5d78c9869d-bp5pq"} 1.6873346599440176e+09 1687334659944
container_start_time_seconds{container="etcd",namespace="kube-system",pod="etcd-kind-control-plane"} 1.6873346136721165e+09 1687334613672
container_start_time_seconds{container="kindnet-cni",namespace="kube-system",pod="kindnet-d6594"} 1.6873346433692157e+09 1687334643369
container_start_time_seconds{container="kube-apiserver",namespace="kube-system",pod="kube-apiserver-kind-control-plane"} 1.6873346073640504e+09 1687334607364
container_start_time_seconds{container="kube-controller-manager",namespace="kube-system",pod="kube-controller-manager-kind-control-plane"} 1.6873346074667194e+09 1687334607466
container_start_time_seconds{container="kube-proxy",namespace="kube-system",pod="kube-proxy-nsk4c"} 1.6873346399998746e+09 1687334639999
container_start_time_seconds{container="kube-scheduler",namespace="kube-system",pod="kube-scheduler-kind-control-plane"} 1.6873346067810647e+09 1687334606781
container_start_time_seconds{container="local-path-provisioner",namespace="local-path-storage",pod="local-path-provisioner-6bc4bddd6b-wq2jp"} 1.687334661040165e+09 1687334661040
# HELP node_cpu_usage_seconds_total [ALPHA] Cumulative cpu time consumed by the node in core-seconds
# TYPE node_cpu_usage_seconds_total counter
node_cpu_usage_seconds_total 107.60794 1687335085102
# HELP node_memory_working_set_bytes [ALPHA] Current working set of the node in bytes
# TYPE node_memory_working_set_bytes gauge
node_memory_working_set_bytes 5.15371008e+08 1687335085102
# HELP pod_cpu_usage_seconds_total [ALPHA] Cumulative cpu time consumed by the pod in core-seconds
# TYPE pod_cpu_usage_seconds_total counter
pod_cpu_usage_seconds_total{namespace="kube-system",pod="coredns-5d78c9869d-9dklc"} 1.302146 1687335076259
pod_cpu_usage_seconds_total{namespace="kube-system",pod="coredns-5d78c9869d-bp5pq"} 1.214503 1687335086671
pod_cpu_usage_seconds_total{namespace="kube-system",pod="etcd-kind-control-plane"} 13.535417 1687335084343
pod_cpu_usage_seconds_total{namespace="kube-system",pod="kindnet-d6594"} 1.144598 1687335073791
pod_cpu_usage_seconds_total{namespace="kube-system",pod="kube-apiserver-kind-control-plane"} 30.265541 1687335072807
pod_cpu_usage_seconds_total{namespace="kube-system",pod="kube-controller-manager-kind-control-plane"} 9.955851 1687335077183
pod_cpu_usage_seconds_total{namespace="kube-system",pod="kube-proxy-nsk4c"} 1.118579 1687335083026
pod_cpu_usage_seconds_total{namespace="kube-system",pod="kube-scheduler-kind-control-plane"} 4.215562 1687335082657
pod_cpu_usage_seconds_total{namespace="local-path-storage",pod="local-path-provisioner-6bc4bddd6b-wq2jp"} 0.733886 1687335084970
# HELP pod_memory_working_set_bytes [ALPHA] Current working set of the pod in bytes
# TYPE pod_memory_working_set_bytes gauge
pod_memory_working_set_bytes{namespace="kube-system",pod="coredns-5d78c9869d-9dklc"} 1.3053952e+07 1687335076259
pod_memory_working_set_bytes{namespace="kube-system",pod="coredns-5d78c9869d-bp5pq"} 1.3389824e+07 1687335086671
pod_memory_working_set_bytes{namespace="kube-system",pod="etcd-kind-control-plane"} 3.1383552e+07 1687335084343
pod_memory_working_set_bytes{namespace="kube-system",pod="kindnet-d6594"} 8.21248e+06 1687335073791
pod_memory_working_set_bytes{namespace="kube-system",pod="kube-apiserver-kind-control-plane"} 2.35442176e+08 1687335072807
pod_memory_working_set_bytes{namespace="kube-system",pod="kube-controller-manager-kind-control-plane"} 4.2266624e+07 1687335077183
pod_memory_working_set_bytes{namespace="kube-system",pod="kube-proxy-nsk4c"} 1.4860288e+07 1687335083026
pod_memory_working_set_bytes{namespace="kube-system",pod="kube-scheduler-kind-control-plane"} 2.1618688e+07 1687335082657
pod_memory_working_set_bytes{namespace="local-path-storage",pod="local-path-provisioner-6bc4bddd6b-wq2jp"} 8.74496e+06 1687335084970
# HELP scrape_error [ALPHA] 1 if there was an error while getting container metrics, 0 otherwise
# TYPE scrape_error gauge
scrape_error 0
```

</p>
</details>
