### ISSUE TITLE
Error when container name has numerical value

### ISSUE THREAD

**Issue by dmitsh** [kubernetes-sigs/kwok#672]
### How to use it?

- [X] kwok
- [ ] kwokctl --runtime=docker (default runtime)
- [ ] kwokctl --runtime=binary
- [ ] kwokctl --runtime=nerdctl
- [ ] kwokctl --runtime=kind

### What happened?

I deployed `kwok-controller` in an existing minikube cluster (https://kwok.sigs.k8s.io/docs/user/kwok-in-cluster), and successfully added a fake node.
When deploying a pod, I can see that the pod has been scheduled on the fake node, but its status remains Pending.
```
$ kubectl get po -o wide
NAME   READY   STATUS    RESTARTS   AGE     IP       NODE          NOMINATED NODE   READINESS GATES
1      0/2     Pending   0          2m18s   <none>   kwok-node-0   <none>           <none>
```

Any recommendations on how to troubleshoot?

### What did you expect to happen?

I expect the pod to be in the Running status

### How can we reproduce it (as minimally and precisely as possible)?

Deploy kwok-controller in a minikube cluster, add a fake node, deploy a pod, check the pod status.

### Kwok version

<details>

$ kubectl -n kube-system describe deploy kwok-controller
Name:                   kwok-controller
Namespace:              kube-system
CreationTimestamp:      Wed, 21 Jun 2023 16:42:42 -0700
Labels:                 app=kwok-controller
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=kwok-controller
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=kwok-controller
  Service Account:  kwok-controller
  Containers:
   kwok-controller:
    Image:      registry.k8s.io/kwok/kwok:v0.3.0
    Port:       <none>
    Host Port:  <none>
    Args:
      --manage-all-nodes=false
      --manage-nodes-with-annotation-selector=kwok.x-k8s.io/node=fake
      --manage-nodes-with-label-selector=
      --disregard-status-with-annotation-selector=kwok.x-k8s.io/status=custom
      --disregard-status-with-label-selector=
      --node-ip=$(POD_IP)
      --node-port=10247
      --cidr=10.0.0.1/24
      --node-lease-duration-seconds=40
    Liveness:   http-get http://:10247/healthz delay=2s timeout=2s period=10s #success=1 #failure=3
    Readiness:  http-get http://:10247/healthz delay=2s timeout=2s period=20s #success=1 #failure=5
    Environment:
      POD_IP:   (v1:status.podIP)
    Mounts:    <none>
  Volumes:     <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   kwok-controller-787c54f4fd (1/1 replicas created)
Events:          <none>

</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux linux 5.15.0-75-generic #82~20.04.1-Ubuntu SMP Wed Jun 7 19:37:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```
</details>

**Comment by dmitsh** [comment]
More details:

The error happens when a container has numerical value, for example:
```
apiVersion: v1
kind: Pod
metadata:
  name: "2"
  namespace: default
  labels:
    app: fake-pod
spec:
  containers:
  - name: "2"
    image: fake
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: In
            values:
            - kwok-controller
  tolerations:
    - key: "kwok-controller/provider"
      operator: "Exists"
      effect: "NoSchedule"
```
The controller log shows
```
{"time":"2023-06-22T19:11:58.358616255Z","level":"ERROR","source":{"function":"sigs.k8s.io/kwok/pkg/kwok/controllers.(*PodController).playStage","file":"/workspace/pkg/kwok/controllers/pod_controller.go","line":391},"msg":"Failed to configure pod","id":"kwok-controller-787c54f4fd-h58cq_a5f53a27-dd17-4a31-95b1-515d74e25fe3","pod":"default/2","node":"kwok-gpu-node","stage":"pod-ready","err":"json: cannot unmarshal number into Go struct field ContainerStatus.containerStatuses.name of type string"}
```
