### ISSUE TITLE
Add a configuration

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#68]
``` yaml
# ~/.kwok/kwok.yml
kind: KwokConfiguration
apiVersion: kwok.x-k8s.io/v1alpha1
spec:
  cidr: ""
  disregardStatusWithAnnotationSelector: ""
  disregardStatusWithLabelSelector: ""
  manageAllNodes: false
  manageNodesWithAnnotationSelector: ""
  manageNodesWithLabelSelector: ""
  nodeIP: ""
```

``` yaml
# ~/.kwok/kwokctl.yml
kind: KwokctlConfiguration
apiVersion: kwok.x-k8s.io/v1alpha1
spec:
  workdir: ""
  kubeApiserverPort: 0
  runtime: ""
  prometheusPort: 0
  kwokVersion: ""
  kubeVersion: ""
  etcdVersion: ""
  prometheusVersion: ""
  securePort: false
  quietPull: false
  kubeImagePrefix: ""
  etcdImagePrefix: ""
  kwokImagePrefix: ""
  prometheusImagePrefix: ""
  etcdImage: ""
  kubeApiserverImage: ""
  kubeControllerManagerImage: ""
  kubeSchedulerImage: ""
  kwokControllerImage: ""
  prometheusImage: ""
  kindNodeImagePrefix: ""
  kindNodeImage: ""
  kubeBinaryPrefix: ""
  kubeApiserverBinary: ""
  kubeControllerManagerBinary: ""
  kubeSchedulerBinary: ""
  kubectlBinary: ""
  etcdBinaryPrefix: ""
  etcdBinary: ""
  etcdBinaryTar: ""
  kwokBinaryPrefix: ""
  kwokControllerBinary: ""
  prometheusBinaryPrefix: ""
  prometheusBinary: ""
  prometheusBinaryTar: ""
  mode: ""
  kubeFeatureGates: ""
  kubeRuntimeConfig: ""
  kubeAuditPolicy: ""
  kubeAuthorization: ""
```

Pod lifecycle simulation configuration #67
