### ISSUE TITLE
[WIP] kwokctl play command and Scenario API

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#725]
### What would you like to be added?

```
kwokctl play scheduling-basic
kwokctl play scheduling-basic --param .initNodes=500 --param .initPods=500
kwokctl play scheduling-basic --play 500Nodes
```

The expression of --params content is JQ

``` yaml
apiVersion: config.kwok.x-k8s.io/v1alpha1
kind: KwokctlScenario
metadata:
  name: scheduling-basic
steps:
- name: Environment Prepare
  run: Resource("node").Scale(initNodes) && Resource("pod").Scale(initPods)
- name: Have a rest before measure
  run: SleepSecond(5)
- name: Start Measure
  run: StartMeasure()
- name: Measure Pods
  run: Resource("pod").Scale(initPods+measurePods)
- name: End Measure
  run: EndMeasure()
parameters:
  measurePods: 1000
plays:
- name: 500Nodes
  parameters:
    initNodes: 500
    initPods: 500
- name: 5000Nodes
  parameters:
    initNodes: 5000
    initPods: 1000
```

The expression of run content is CEL

### Why is this needed?

https://github.com/kubernetes/kubernetes/blob/f33498a8256b455b677ad4d30440869318b84204/test/integration/scheduler_perf/README.md

Easy to mock data
