### ISSUE TITLE
ResourceUsage API

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#737]
### What would you like to be added?

``` yaml
kind: ResourceUsage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: pod
  namespace: default
spec:
  usages:
  - usage:
      cpu: container.resources.requests.cpu || 100m
      # Take the value from the annotation and divide it equally between each container.
      # cpu: Quantity(pod.metadata["cpu_usage"]) / len(pod.spec.containers)
      # Each container uses one-tenth of the host node
      # cpu: node.status.allocatable.cpu / 10.0
      # Value from annotations
      # cpu: '"kwok.x-k8s.io/usage-cpu" in pod.metadata.annotations ? Quantity(pod.metadata.annotations["kwok.x-k8s.io/usage-cpu"]) : Quantity("1m")'
      
      memory: container.resources.requests.memory || 100Mi
      # Memory keeps growing
      # memory: Quantity(pod.SinceSecond()) * 1Mi
      # Value from annotations
      # memory: '"kwok.x-k8s.io/usage-memory" in pod.metadata.annotations ? Quantity(pod.metadata.annotations["kwok.x-k8s.io/usage-memory"]) : Quantity("1Mi")'
---
kind: ClusterResourceUsage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: cluster-resource-usage
spec:
...

```

examples

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  maxReplicas: 10
  minReplicas: 1
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        value: 100
        periodSeconds: 3
      selectPolicy: Max
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 2
      - type: Pods
        value: 2
        periodSeconds: 2
      selectPolicy: Max
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
kind: ClusterResourceUsage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: cluster-resource-usage
spec:
  usages:
  - usage:
      cpu: 100m
      memory: 100Mi
```

### Why is this needed?

Need a simple way to describe resource usage for Pod
