### ISSUE TITLE
Add selector.matchExtraResources into Stage API

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#977]
### What would you like to be added?

Add Trigger API allow to modify any resources

### Why is this needed?

Closer to Kubelet

**Comment by wzshiming** [comment]
```
# oom.yaml
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Trigger
metadata:
  name: oom
spec:
  resourceRef:
    apiGroup: custom.metrics.k8s.io/v1beta2
    kind: MetricValue

  targets:
  - resourceRef:
      apiGroup: v1
      kind: Pod
    selector:
      matchCEL:
      - expression: |
          self.metadata.name == target.metadata.name &&
          self.metadata.namespace == target.metadata.namespace &&
          OOM(self.spec.containers, target.spec.containers)

    patches:
    - subresource: status
      root: status
      type: merge
      template: |
        {{ $now := Now }}
        {{ $root := . }}
        conditions:
        - lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
          message: ''
          reason: ''
          status: "False"
          type: Ready
        - lastProbeTime: null
          lastTransitionTime: {{ $now | Quote }}
          message: ''
          reason: ''
          status: "True"
          type: OutOfMemory
        containerStatuses:
        {{ range $index, $item := .spec.containers }}
        {{ $origin := index $root.status.containerStatuses $index }}
        - image: {{ $item.image | Quote }}
          name: {{ $item.name | Quote }}
          ready: false
          restartCount: {{ $origin.restartCount }}
          started: false
          state:
            terminated:
              exitCode: 137
              finishedAt: {{ $now | Quote }}
              reason: OOMKilled
              startedAt: {{ $now | Quote }}
        {{ end }}
        phase: Failed
```

**Comment by wzshiming** [comment]
```yaml
# node-image-exists.yaml
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Trigger
metadata:
  name: node-image-exists
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchCEL:
    - expression: 'self.status.phase in ["ContainerCreating", "Running"]'

  targets:
  - resourceRef:
      apiGroup: v1
      kind: Node
    selector:
      matchCEL:
      - expression: 'target.metadata.name == self.spec.nodeName'

    patches:
    - subresource: status
      root: status
      type: merge
      template: |
        {{ $exist := list }}
        images:
        {{ range .target.status.images }}
        - names:
          {{ range .names }}
          {{ $exist = append $exist . }}
          - {{ . | Quote }}
          {{ end }}
          {{ if .sizeBytes }}
          sizeBytes: {{ .sizeBytes }}
          {{ end }}
        {{ end }}
        {{ range .resource.spec.containers }}
        {{ if not (in $exist .image) }}
        - names:
          - {{ .image | Quote }}
        {{ end }}
        {{ end }}
```
